/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package studio.forface.recruiteetodoist

import com.amazonaws.services.lambda.runtime.Context
import com.amazonaws.services.lambda.runtime.RequestHandler
import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.joinAll
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import studio.forface.recruiteetodoist.domain.usecase.GetUpcomingInterviews
import studio.forface.recruiteetodoist.domain.usecase.PostInterviewTask

open class App(
    val getUpcomingInterviews: GetUpcomingInterviews = GetUpcomingInterviews(),
    val postInterviewTask: PostInterviewTask = PostInterviewTask()
) {

    suspend fun syncInterviews() = coroutineScope {
        val jobs = getUpcomingInterviews().upcoming.map { interview ->
            launch { postInterviewTask(interview) }
        }

        joinAll(*jobs.toTypedArray())
    }
}

class AwsApp : App(), RequestHandler<EmptyHandler, String> {

    override fun handleRequest(input: EmptyHandler, context: Context): String {
        var result = ""

        runBlocking {
            result = try {
                syncInterviews()
                "success"
            } catch (t: Throwable) {
                "failure: ${t.message}"
            }
        }

        return result
    }
}

suspend fun main(args: Array<String>) {
    val app = AwsApp()

    app.syncInterviews()
}


val RECRUITEE_COMPANY_ID: String? = System.getenv("RECRUITEE_COMPANY_ID")
val RECRUITEE_TOKEN: String? = System.getenv("RECRUITEE_TOKEN")
val TODOIST_TOKEN: String? = System.getenv("TODOIST_TOKEN")
