/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package studio.forface.recruiteetodoist

import kotlinx.coroutines.coroutineScope
import kotlinx.coroutines.joinAll
import kotlinx.coroutines.launch
import studio.forface.recruiteetodoist.domain.usecase.GetUpcomingInterviews
import studio.forface.recruiteetodoist.domain.usecase.PostInterviewTask

class App(
    val getUpcomingInterviews: GetUpcomingInterviews = GetUpcomingInterviews(),
    val postInterviewTask: PostInterviewTask = PostInterviewTask()
) {

    suspend fun syncInterviews() = coroutineScope {
        val jobs = getUpcomingInterviews().upcoming.map { interview ->
            launch { postInterviewTask(interview) }
        }

        joinAll(*jobs.toTypedArray())
    }
}

suspend fun main(args: Array<String>) {
    val app = App()

    app.syncInterviews()
}


val RECRUITEE_COMPANY_ID: String? = System.getenv("RECRUITEE_COMPANY_ID")
val RECRUITEE_TOKEN: String? = System.getenv("RECRUITEE_TOKEN")
val TODOIST_TOKEN: String? = System.getenv("TODOIST_TOKEN")
